POST http://localhost:8080/words
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGVtYWlsLmNvbSIsImV4cCI6MTcwNTE5MjA0NSwidXNlcklkIjoyfQ.BfVrXXDMlbdNtl9Sb03f3OVuARVAWWbNjxUJqzHC6lg


{
    "mot": "sdfasdfdf",
    "livre": "Ulysses",
    "page": "35",
    "dateTime": "2025-01-01T15:30:30:00.000Z"
}